# Generated by Django 5.2.1 on 2025-05-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='nttc_qualificatio',
            new_name='nttc_qualification',
        ),
    ]
