# Generated by Django 5.2.1 on 2025-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_remove_qualification_nttc_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='certificate_name',
            field=models.CharField(default='NC Level Unknown', max_length=150),
        ),
    ]
