# Generated by Django 5.2.1 on 2025-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_remove_qualification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
