# Generated by Django 5.2.1 on 2025-06-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_trainer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(auto_now_add=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.qualification')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'qualification')},
            },
        ),
    ]
