# Generated by Django 5.2.1 on 2026-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_assessor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='assessor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='assessor',
            name='region',
        ),
        migrations.AddField(
            model_name='assessor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assessor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assessor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='assessor',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='qualification',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
