# Generated by Django 5.2.1 on 2026-03-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_assessorqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessorqualification',
            name='nttc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
