# Generated by Django 5.2.1 on 2026-04-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_alter_assessorqualification_nttc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessorqualification',
            name='title',
        ),
    ]
