# Generated by Django 5.2.1 on 2025-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_nttc_qualificatio_qualification_nttc_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='nttc_qualification',
        ),
        migrations.AddField(
            model_name='qualification',
            name='certificate_name',
            field=models.CharField(default='NC Level Unknow', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('For Renewal', 'For Renewal')], default='Active', max_length=20),
        ),
    ]
