# Generated by Django 5.2.1 on 2025-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_qualification_certificate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='status',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='certificate_name',
            field=models.CharField(default='Qualification Title', max_length=150),
        ),
    ]
