# Generated by Django 5.2.1 on 2026-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_emaillog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emaillog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_for_days_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='emaillog',
            unique_together={('trainer', 'qualification', 'sent_for_days_before')},
        ),
    ]
