# Generated by Django 5.2.1 on 2026-03-30 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_remove_assessor_date_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('nttc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='trainer.assessor')),
            ],
        ),
    ]
